export const START_COUNTDOWN = 'START_COUNTDOWN',
	STOP_COUNTDOWN = 'STOP_COUNTDOWN',
	CONTINUE_COUNTDOWN = 'CONTINUE_COUNTDOWN',
	SET_COUNTDOWN_TIME = 'SET_COUNTDOWN_TIME',
	DECREMENT_COUNTDOWN_TIME = 'DECREMENT_COUNTDOWN_TIME',
	ENABLE_COUNTDOWN = 'ENABLE_COUNTDOWN';
