export const START_GAME = 'START_GAME',
	STOP_GAME = 'STOP_GAME',
	CONTINUE_GAME = 'CONTINUE_GAME',
	GAME_WON = 'GAME_WON',
	GAME_LOST = 'GAME_LOST',
	SET_CONTROLS_DESCRIPTION = 'SET_CONTROLS_DESCRIPTION';
